version: 2

project_name: helm-api

before:
  hooks:
  - go mod tidy

builds:
- env: ["CGO_ENABLED=0"]
  binary: helm-api
  goos:
  - linux
  goarch:
  - amd64
  - arm64

kos:
- repositories: ["ghcr.io/appkins-org/{{.ProjectName}}"]
  tags:
  - latest
  - "{{.ShortCommit}}"
  - "{{if not .IsSnapshot}}{{.Version}}{{end}}"
  bare: false
  preserve_import_paths: false
  platforms:
  - linux/amd64
  - linux/arm64
  disable: false
  base_image: scratch
  local_domain: ghcr.io

docker_signs:
- artifacts: manifests
