version: 2

project_name: helm-api

before:
  hooks:
  - go mod tidy

kos:
- repositories: [ghcr.io/appkins-org/helm-api]
  tags:
  - "{{.Version}}"
  - latest
  bare: true
  preserve_import_paths: false
  platforms:
  - linux/amd64
  - linux/arm64
